name: Deploy Production
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Apply configuration
        run: |
          git clone https://oauth2:${{ secrets.CONFIG_REPOSITORY_TOKEN }}@github.com/meetdy/infrastructure-config.git
          [ -e .env ] && rm .env
          [ -e Dockerfile ] && rm Dockerfile
          cp infrastructure-config/meetdy-frontend/.env ./
          cp infrastructure-config/meetdy-frontend/Dockerfile ./
      
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Set version variable
        id: vars
        run: echo "VERSION=$(date +%s)" >> $GITHUB_ENV

      - name: Build the Docker image with both tags
        run: |
          docker build . --file Dockerfile --tag nghiaphamln/meetdy-frontend:latest \
          --tag nghiaphamln/meetdy-frontend:${{ env.VERSION }}

      - name: Push the Docker image to Docker Hub
        run: |
          docker push nghiaphamln/meetdy-frontend:${{ env.VERSION }}
          docker push nghiaphamln/meetdy-frontend:latest

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Pull and restart Docker Compose on VPS
        env:
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
          sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no -t $VPS_USER@$VPS_HOST << EOF
            cd ./docker/meetdy-frontend || exit
            docker compose pull
            docker compose down
            docker compose up -d
            docker image prune -f
            docker images | grep 'nghiaphamln/meetdy-frontend' | awk '{if(NR>1) print \$3}' | xargs -r docker rmi -f
          EOF
